### PR TITLE
Minor improvements to avoid out of memory issues in stable_diffusion.ipynb notebook.

### PR DESCRIPTION
**Pull request by jantic**
Removing unnecessary additional memory usage by replacing separate Dreambooth db_pipe assignment with pipe, and then deleting that pipe before running "Looking inside the pipeline" section. This allows me to run notebook all the way through without out of memory issues on a 12 GB 3080TI card.

I should note that this assumes that using the Dreambooth pipeline for the "What is Stable Diffusion" section is an acceptable substitution, and that the output example has changed as a result.

### CODE REVIEW

**Comment by jantic** [comment]
Added one more commit that sets models in "Looking inside the pipeline" to fp16 to further memory efficiency and allow for running the notebook beginning to end on a 11GB 1080TI gpu.

**Comment by jph00** [comment]
Thanks mate! Any chance you could reduce the size of this PR by not re-running the image outputs, and also not run that cell that gives you the `ls` error? (If that's not convenient no worries I can always just edit it at my end)

**Comment by jantic** [comment]
Oh sure thing,. Done. It was checked in with outputs originally so that's what I assumed was wanted for the pull request. Otherwise I wouldn't normally do that as yeah- that makes for a lot of extra data in git.

**Comment by jph00** [comment]
Sorry I didn't explain myself carefully enough. We do still want the outputs (so that people can see them in the notebook without running it, which takes some time), but I was hoping you could avoid *re-running* the notebook from the version in the repo. That way, the outputs aren't regenerated with slightly different pixels (which makes the PR and repo bigger). Does that make sense?

**Comment by jantic** [comment]
Yeah that's clear now. I'll have this done tomorrow here in the US. Sorry about that!

**Comment by jantic** [comment]
It seemed a bit over complicated to try to modify the existing pull request/branch to get rid of the junk history, so I make a new pull request here that I think should work:  [https://github.com/fastai/diffusion-nbs/pull/5](https://github.com/fastai/diffusion-nbs/pull/5) .  Closing this version.

**Pull request closed without merging**
