### PR TITLE
Adding small section on enable attention slicing

### PR DESCRIPTION
**Pull request by kevinbird15**
It was suggested on the forum to add a small section to explain the pipe.enable_attention_slicing() line and make sure users are aware of the ability if their GPU is too small to run stable diffusion out of the box.  I have gotten this to work with a 4 GB GPU (3050M) using enable_attention_slicing.  Wasn't able to get all the way through the notebook, but could at least generate images.

### CODE REVIEW

**Comment by pcuenca** [comment]
Hi @kevinbird15 that's awesome! Would it be possible for you to submit just the source for the new cell without changing any of the outputs?

**Comment by kevinbird15** [comment]
Yeah, let me fix that.  I thought I had already...  Fix incoming

**Comment by kevinbird15** [comment]
@pcuenca I am not sure why, but all of the images show that they have changed.  Any idea why that would be or how I can reset them?  I tried this: 
`git checkout master -- stable_diffusion.ipynb`

Then I re-entered only the two cells I actually wanted to change, but all of the images still look as if they have been modified.

**Comment by kevinbird15** [comment]
This is done now. 

First, I ran `git reset --hard HEAD~2` to revert my two changes I had made, Then I re-applied my changes and the images were still different. I then used vs-code to revert the images from being changed.  Not sure how to do it otherwise, but once that was done, I just did `git push --force` to apply the modifications.  Should be good to go now!

**Pull request merged**
